apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: bookshop #update
  # name: bookshop-1 #update
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: 715ab873trial-bookshop-approuter-default #update
  # host: trial-1-g79zgtcn-bookshop-approuter-default #update
  service:
    name: bookshop-approuter #update
    port: 8080
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*