apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: bookshop #update
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: bookshop-approuter-default #update
  service:
    name: bookshop-approuter #update
    port: 8080
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*